insert into artist(id, name) values (1, 'Guns N Roses');
insert into artist(id, name) values (2, 'Foo Fighters');
insert into artist(id, name) values (3, 'Iron Maiden');
insert into artist(id, name) values (4, 'Ramones');
insert into artist(id, name) values (5, 'Pearl Jam');
insert into artist(id, name) values (6, 'Aerosmith');
insert into artist(id, name) values (7, 'Nirvana');
insert into artist(id, name) values (8, 'The Offspring');
insert into artist(id, name) values (9, 'Red Hot Chili Peppers');
insert into artist(id, name) values (10, 'Green Day');
insert into song(id, name, artist_id) values (1, 'Welcome To The Jungle', 1);
insert into song(id, name, artist_id) values (2, 'Patience', 1);
insert into song(id, name, artist_id) values (3, 'November Rain', 1);
insert into song(id, name, artist_id) values (4, 'Paradise City', 1);
insert into song(id, name, artist_id) values (5, 'Civil War', 1);
insert into song(id, name, artist_id) values (6, 'Times Like These', 2);
insert into song(id, name, artist_id) values (7, 'Everlong', 2);
insert into song(id, name, artist_id) values (8, 'My Hero', 2);
insert into song(id, name, artist_id) values (9, 'Learn To Fly', 2);
insert into song(id, name, artist_id) values (10, 'Best Of You', 2);
insert into song(id, name, artist_id) values (11, 'Fear Of The Dark', 3);
insert into song(id, name, artist_id) values (12, 'Wasting Love', 3);
insert into song(id, name, artist_id) values (13, 'The Number Of The Beast', 3);
insert into song(id, name, artist_id) values (14, 'Hallowed Be Thy Name', 3);
insert into song(id, name, artist_id) values (15, 'The Trooper', 3);
insert into song(id, name, artist_id) values (16, 'Poison Heart', 4);
insert into song(id, name, artist_id) values (17, 'Pet Sematary', 4);
insert into song(id, name, artist_id) values (18, 'I Wanna Be Sedated', 4);
insert into song(id, name, artist_id) values (19, 'Blitzkrieg Bop', 4);
insert into song(id, name, artist_id) values (20, 'I Believe In Miracles', 4);
insert into song(id, name, artist_id) values (21, 'Rockaway Beach', 4);
insert into song(id, name, artist_id) values (22, 'Beat On The Brat', 4);
insert into song(id, name, artist_id) values (23, 'I Remember You', 4);
insert into song(id, name, artist_id) values (24, 'I Wanna Be Your Boyfriend', 4);
insert into song(id, name, artist_id) values (25, 'Today Your Love, Tomorrow The World', 4);
insert into song(id, name, artist_id) values (26, 'Black', 5);
insert into song(id, name, artist_id) values (27, 'Alive', 5);
insert into song(id, name, artist_id) values (28, 'Last Kiss', 5);
insert into song(id, name, artist_id) values (29, 'Even Flow', 5);
insert into song(id, name, artist_id) values (30, 'Jeremy', 5);
insert into song(id, name, artist_id) values (31, 'Dream On', 6);
insert into song(id, name, artist_id) values (32, 'Crazy', 6);
insert into song(id, name, artist_id) values (33, 'Hole In My Soul', 6);
insert into song(id, name, artist_id) values (34, 'Sing For The Moment', 6);
insert into song(id, name, artist_id) values (35, 'Jaded', 6);
insert into song(id, name, artist_id) values (36, 'Smells Like Teen Spirit', 7);
insert into song(id, name, artist_id) values (37, 'Come As You Are', 7);
insert into song(id, name, artist_id) values (38, 'Lithium', 7);
insert into song(id, name, artist_id) values (39, 'The Man Who Sold The World', 7);
insert into song(id, name, artist_id) values (40, 'About A Girl', 7);
insert into song(id, name, artist_id) values (41, 'Self Esteem', 8);
insert into song(id, name, artist_id) values (42, 'Pretty Fly (For A White Guy)', 8);
insert into song(id, name, artist_id) values (43, 'Gone Away', 8);
insert into song(id, name, artist_id) values (44, 'Want You Bad', 8);
insert into song(id, name, artist_id) values (45, 'Come Out And Play', 8);
insert into song(id, name, artist_id) values (46, 'Californication', 9);
insert into song(id, name, artist_id) values (47, 'Scar Tissue', 9);
insert into song(id, name, artist_id) values (48, 'Otherside', 9);
insert into song(id, name, artist_id) values (49, 'Under The Bridge', 9);
insert into song(id, name, artist_id) values (50, 'By The Way', 9);
insert into song(id, name, artist_id) values (51, 'Wake Me Up When September Ends', 10);
insert into song(id, name, artist_id) values (52, 'Boulevard Of Broken Dreams', 10);
insert into song(id, name, artist_id) values (53, 'Basket Case', 10);
insert into song(id, name, artist_id) values (54, 'American Idiot', 10);
insert into song(id, name, artist_id) values (55, 'When I Come Around', 10);