schema: 'main/java/resources/graphql/schema.graphqls'
documents: '**/*.graphql'
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: http://localhost:8080/graphql
      headers:
        user-agent: Spring for GraphQL
      introspect: false